<?php

namespace AppBundle\Repository;

/**
 * ApiResultsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiResultsRepository extends \Doctrine\ORM\EntityRepository
{
}
