<?php

namespace AppBundle\Repository;

/**
 * KurBilgisiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KurBilgisiRepository extends \Doctrine\ORM\EntityRepository
{
}
